services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: abderrazak
      POSTGRES_PASSWORD: abderrazak
      POSTGRES_DB: mtoRisk
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mtoRisk-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ana@ana.com
      PGADMIN_DEFAULT_PASSWORD: ana
    ports:
      - "5050:80"
    networks:
      - mtoRisk-network
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  mtoRisk-network:
    driver: bridge